-- MySQL Script generated by MySQL Workbench
-- 12/11/14 01:58:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fg` DEFAULT CHARACTER SET utf8 ;
USE `fg` ;

-- -----------------------------------------------------
-- Table `fg`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fg`.`admin` (
  `idadmin` INT(11) NOT NULL AUTO_INCREMENT,
  `nomecompleto` CHAR(80) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idadmin`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fg`.`cad_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fg`.`cad_usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nomecompleto` CHAR(80) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(12) NOT NULL,
  `celular` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fg`.`anotacao_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fg`.`anotacao_usuario` (
  `idanotacao` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `conteudo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idanotacao`),
  INDEX `fk_idusuario_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_idusuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `fg`.`cad_usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fg`.`cad_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fg`.`cad_materia` (
  `idmateria` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `carga_horaria` INT(11) NULL DEFAULT NULL,
  `nome_prof` CHAR(45) NULL DEFAULT NULL,
  `id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`idmateria`),
  INDEX `fk_Aluno_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `fg`.`cad_usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fg`.`pauta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fg`.`pauta` (
  `idpauta` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `horas` DECIMAL(10,0) NOT NULL,
  `id_materia` INT(11) NOT NULL,
  `id_usu` INT(11) NOT NULL,
  PRIMARY KEY (`idpauta`),
  INDEX `fk_materia_idx` (`id_materia` ASC),
  INDEX `id_usu_idx` (`id_usu` ASC),
  CONSTRAINT `fk_materia`
    FOREIGN KEY (`id_materia`)
    REFERENCES `fg`.`cad_materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usu`
    FOREIGN KEY (`id_usu`)
    REFERENCES `fg`.`cad_usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;

USE `fg` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Insert Admin
-- -----------------------------------------------------

INSERT INTO `fg`.`admin` (`nomecompleto`, `email`, `senha`) VALUES ('Administrador', 'admin@admin.com', '12345');
INSERT INTO `fg`.`admin` (`nomecompleto`, `email`, `senha`) VALUES ('Administrador2', 'admin2@admin.com', '12345');
INSERT INTO `fg`.`admin` (`nomecompleto`, `email`, `senha`) VALUES ('Administrador3', 'admin3@admin.com', '12345');

-- -----------------------------------------------------
-- Insert Usuario
-- -----------------------------------------------------

INSERT INTO `fg`.`cad_usuario` (`nomecompleto`, `email`, `senha`, `celular`) VALUES ('Usuario', 'usuario@usuario.com', '12345', '(33)33333-3333');
INSERT INTO `fg`.`cad_usuario` (`nomecompleto`, `email`, `senha`, `celular`) VALUES ('Usuario2', 'usuario2@usuario.com', '12345', '(22)22222-2222');
INSERT INTO `fg`.`cad_usuario` (`nomecompleto`, `email`, `senha`, `celular`) VALUES ('Usuario3', 'usuario3@usuario.com', '12345', '(44)44444-4444');
